apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "KarpenterNodeRole-<CLUSTER-NAME>" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "<CLUSTER-NAME>" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "<CLUSTER-NAME>" # replace with your cluster name
  amiSelectorTerms:
    - id: "ami-033e03ec486b5d22f"
    - id: "ami-0e4bab9adfcf464b1"
