apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: custom-nodepool
spec:
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: custom-ec2nodeclass
      requirements:
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot", "on-demand"]
      - key: "node.kubernetes.io/instance-type"
        operator: In
        values: ["m6a.large", "m6a.xlarge", "t3a.xlarge"]
      kubelet:
        imageGCHighThresholdPercent: 80
        imageGCLowThresholdPercent: 40
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  limits:
    cpu: 1000
    memory: 1000Gi
  weight: 100
